name = "wallpapers-api"
main = "index.js"
compatibility_date = "2025-01-01"

# Only this origin may call the API.
[vars]
ALLOW_ORIGIN = "https://john-wallpapers.pages.dev"

[[kv_namespaces]]
binding = "KV"
id      = "7643a77b423546989beb008fd55dc69f"
